name: code coverage
on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Get latest cmake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S . -B build -D CMAKE_CXX_COMPILER=g++-13 -D "CMAKE_CXX_FLAGS=--coverage -g -O0" -D VCPKG_TARGET_TRIPLET=x64-linux --toolchain "${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --parallel

      - name: Execute
        run: ctest --test-dir build

      - name: Install gcovr
        run: |
          sudo apt-get update
          sudo apt-get install -yq gcovr
          sudo apt-get clean

      - name: Generate a code coverage report
        uses: threeal/gcovr-action@v1.0.0
        with:
          coverall-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
