name: code coverage
on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Get latest cmake
        uses: lukka/get-cmake@latest

      - name: Install gcovr
        run: |
          sudo apt-get update
          sudo apt-get install -yq python3-pip
          sudo apt-get clean
          pip install gcovr
          gcovr --version

      - name: Configure
        run: cmake -S . -B build -D CMAKE_CXX_COMPILER=g++-13 -D "CMAKE_CXX_FLAGS=--coverage -g -O0" -D VCPKG_TARGET_TRIPLET=x64-linux --toolchain "${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --parallel

      - name: Execute
        run: ctest --test-dir build

      - name: Create report
        run: |
          mkdir html
          gcovr --filter include/io1/money.hpp --exclude-unreachable-branches --exclude-lines-by-pattern '.*assert.*' --print-summary -x coverage.xml --html-details html/index.html --html-details-syntax-highlighting -r . build

      - uses: actions/upload-artifact@v3
        with:
          name: detailed coverage report
          path: html

      - uses: 5monkeys/cobertura-action@v13
        with:
          path: coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 84
          fail_below_threshold: true
          show_line: true
          show_branch: true
          show_missing: true
