name: code coverage
on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Get latest cmake
        uses: lukka/get-cmake@latest

      - name: Configure
        shell: cmake -P {0}
        run: |
          set(vcpkg_triplet x64-linux)
          set(compiler_flags "--coverage -g -O0")
          set(linker_flags "--coverage")
          set(ENV{CC} "gcc-13")
          set(ENV{CXX} "g++-13")
          execute_process(
            COMMAND cmake
              -S .
              -B build
              -D VCPKG_TARGET_TRIPLET=${vcpkg_triplet}
              -D "CMAKE_CXX_FLAGS=${compiler_flags}"
              -D "CMAKE_LD_FLAGS=${linker_flags}"
              --toolchain "$ENV{VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status")
          endif()

      - name: Build
        run: cmake --build build --parallel

      - name: Execute
        run: ctest --test-dir build

      - name: Install gcovr
        run: |
          sudo apt-get update
          sudo apt-get install -yq gcovr
          sudo apt-get clean

      - name: Create report
        run: |
          mkdir html
          gcovr --filter include/io1/money.hpp --exclude-unreachable-branches --exclude-lines-by-pattern '.*assert.*' --print-summary -x coverage.xml --html-details html/index.html --html-details-syntax-highlighting -r . build

      - uses: 5monkeys/cobertura-action@v13
        with:
          path: coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 84
          fail_below_threshold: true
          show_line: true
          show_branch: true
          show_missing: true

      - uses: actions/upload-artifact@v3
        with:
          name: detailed coverage report
          path: html
