name: code coverage
on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest cmake
        uses: lukka/get-cmake@latest

      - name: Install gcovr
        run: pip install gcovr

      - name: Configure
        env:
          CXXFLAGS: --coverage -fprofile-abs-path -g -O1
          CFLAGS: --coverage -fprofile-abs-path -g -O1
          LDFLAGS: --coverage
          CC: gcc-13
          CXX: g++-13 # gcov (!= gcovr) version should match
        run: cmake -S . -B build -D VCPKG_TARGET_TRIPLET=x64-linux --toolchain "${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --parallel

      - name: Execute
        run: ctest --test-dir build

      - name: Create report
        run: |
          mkdir build/html
          gcovr --gcov-executable /usr/bin/gcov-13 --filter include/io1/money.hpp --exclude-unreachable-branches --exclude-lines-by-pattern '.*assert.*' --print-summary -x build/coverage.xml --html-details build/html/index.html --html-details-syntax-highlighting -r . build

      - uses: actions/upload-artifact@v3
        with:
          name: detailed coverage report
          path: build/html

      - uses: actions/upload-artifact@v3
        with:
          name: cobertura file
          path: build/coverage.xml

      - uses: 5monkeys/cobertura-action@v13
        with:
          path: build/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 83
          fail_below_threshold: true
          show_line: true
          show_branch: true
          show_missing: true
