name: linters
on: [push]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: clang-tidy-15 include/io1/money.hpp --export-fixes=clang-fixes.yaml -- -std=c++20

      - name: Process clang-tidy warnings
        uses: asarium/clang-tidy-action@v1
        with:
          fixesFile: clang-fixes.yaml
